# =========================
# BANKS
# GOV / STATE
# LESTA / WOT / TANKI
# LOCAL / PRIVATE NETWORKS
# MAPS / SECURITY
# Mir Tankov IP
# OPERATORS
# RU ZONE (дублируем для явности)
# SHOPPING / DELIVERY
# STEAM / VALVE
# STREAMING
# Steam / CS2 IP
# TRANSPORT
# VK / MEDIA
# WARTHUNDER / GAIJIN
# WarThunder IP
# YANDEX
0
10.0.0.0/8
100.64.0.0/10
103.10.124.0/23
127.0.0.0/8
146.66.152.0/21
146.66.155.0/24
155.133.224.0/19
162.254.192.0/21
172.16.0.0/12
178.132.192.0/18
185.217.0.0/16
185.25.180.0/22
185.30.176.0/22
192.168.0.0/16
208.64.200.0/22
224.0.0.0/4
2gis.com
2gis.ru
5.8.0.0/16
92.223.0.0/16
92.38.128.0/17
95.211.0.0/16
alfabank.ru
api.worldoftanks.ru
auth.gaijin.net
avito.ru
beeline.ru
cdek.ru
cdn.gaijin.net
citilink.ru
cm.steampowered.com
counter-strike.net
counterstrike.com
csgo.com
customs.gov.ru
dellin.ru
dns-shop.ru
drweb.ru
dzen.ru
eldorado.ru
emex.ru
exist.ru
fsm.sberbank-service.ru
fssp.gov.ru
gaijin.com
gaijin.net
gazprombank.ru
gjt.gg
gosuslugi.gov.ru
gosuslugi.ru
gov.ru
inbox.ru
ivi.ru
kaspersky.ru
lesta-cdn.ru
lesta-game.com
lesta-start.ru
lesta-static.ru
lesta.games
lesta.ru
list.ru
login.gaijin.net
login.pw.worldoftanks.ru
mail.ru
megafon.ru
mil.ru
minfin.ru
more.tv
mos.ru
mosreg.ru
mts.ru
mvideo.ru
my.mail.ru
nalog.ru
ok.ru
okko.tv
ozon.ru
pfr.gov.ru
pochta.ru
rambler.ru
rosreestr.gov.ru
rostelecom.ru
rt.ru
ru
russianpost.ru
rutube.ru
rzd-bonus.ru
rzd.ru
sber.ru
sberbank.ru
sentry-sprint.sberbank-service.ru
spb.ru
static.gaijin.net
steam-chat.com
steamcommunity.com
steamcontent.com
steamgames.com
steampowered.com
steamserver.net
steamstatic.com
su
tanki.su
teamfortress.com
tele2.ru
tinkoff.ru
valve.net
vk.com
vk.ru
vkvideo.ru
vtb.ru
warthunder.com
wildberries.ru
wink.ru
worldoftanks.ru
wot.ru
wot.su
xn--p1ai
ya.ru
yandex.com
yandex.net
yandex.ru
yandexcloud.net
yandexcloud.ru
